version: "3.7"

services:
  web:
    image: ghcr.io/diamondhands-dev/shiro-frontend:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 4444:8080
    volumes:
      - ${APP_DATA_DIR}/tmp/shiro-wallet:/tmp/shiro-wallet